[package]
name = "lithium"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lithium-repl"
path = "src/bin/repl.rs"

[lib]
name = "lithium"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
rustyline = "13.0.0"
